### ISSUE TITLE
Transfer readme

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#4]
link the main readme to individual readme's in templates for each configuration

 - [x] collabora
 - [x] homeassistant
 - [x] minecraft
 - [x] nextcloud
 - [x] phpmyadmin
 - [x] plex
 - [x] portainer
 - [x] samba
 - [x] transmission

Move into wiki pages
 - [x] ddns cron
 - [x] raid setup
 - [x] samba share connect

**Comment by maave0** [comment]
Updated DDNS docs with commit c9dc6c18afa4f12a94f0fe78130965d0e4b4e3cf

Personally I have not bothered with a Wiki yet because I don't have users to update it. Everything goes into /docs
