### ISSUE TITLE
Server looking for certs on apps not enabled

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/docker-nas#71]
# Problem

Server is looking for app certificates that are not enabled
phpmyadmin.example.com

```
logs here
```

## Solution

Don't search/validate certificates on disabled apps

## Details

Provide as much as you can below.

- App Version: v3 8ad395cbb602fc0b3b2d3347d0f26a553004ddae

**Comment by ldrrp** [comment]
Added simple check if app.Enabled then do the cert check. otherwise ignore
