### ISSUE TITLE
Check for Docker install at the beginning, not during app startup

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/docker-nas#72]
# Problem

On a fresh install, the setup fails when Docker isn't present. 

## Solution

It's supposed to prompt to install Docker. The prompt is on starting apps instead

## Details

v3

**Comment by maave0** [comment]
Another example is running `server.bin -daemon install`

**Comment by ldrrp** [comment]
Moved this over to main() instead of apps.Start()
