### ISSUE TITLE
nginx order of operations

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/docker-nas#73]
# Problem

order of operations issue

2022/08/27 01:44:41 add template for /docker-nas/docker-data/nginx/templates/nextcloud.apps.conf.template
2022/08/27 01:44:41 Could not copy nginx.conf template for nextcloud: open /docker-nas/docker-data/nginx/templates/nextcloud.apps.conf.template: no such file or directory

**Comment by ldrrp** [comment]
Fixed this by moving before-start just before nginxssl function. This should allow any apps to create needed directories as part of before-start.sh files
